apiVersion: v1
kind: Service
metadata:
  name: monitoring-app-service
spec:
  selector:
    app: monitoring-app
  ports:
    - protocol: TCP
      port: 80  # The port on which the service will be exposed
      targetPort: 80  # The port that your application is listening on inside the container
  type: LoadBalancer  # This creates an external IP for accessing the service